### ISSUE TITLE
Complete `alr settings` refactor

### ISSUE THREAD

**Issue by mosteo** [alire-project/alire#1621]
- [x] -c (--config=ARG)       Override configuration folder location global switch (#1627)
- [x] .alire/config.toml file (#1626)
- [x] ALR_CONFIG scenario variable (#1625)
- [x] Rename of Alire.Config.* packages (#1622)
- [x] Default folder ~/.config/ (on Windows) (#1624)
